{
  config,
  pkgs,
  ...
}:

{
  home = {
    file."${config.xdg.configHome}/niri/config.kdl".source = ./niri.kdl;
    file."${config.xdg.configHome}/niri/colors.kdl".source =
      let
        borderColors =
          if config.stylix.enable then
            {
              active = config.lib.stylix.colors.base0D;
              inactive = config.lib.stylix.colors.base03;
            }
          else
            {
              active = "#ffffff";
              inactive = "#212121";
            };
      in
      pkgs.writeText "colors.kdl" ''
        // Generated by stylix
        active-color "${borderColors.active}"
        inactive-color "${borderColors.inactive}"
      '';
  };

  # workaraound for Apple backlight not working on boot
  systemd.user.services.fix-apple-backlight = {
    Unit = {
      Description = "Power cycle display to fix Apple backlight on boot";
      After = [ "graphical.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.bash}/bin/bash -c 'niri msg action power-off-monitors; sleep 1; niri msg action power-on-monitors'";
    };
    Install = {
      WantedBy = [ "graphical.target" ];
    };
  };
}
