# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6fcadafb-09dc-4e69-926c-608acb0798f7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6fcadafb-09dc-4e69-926c-608acb0798f7".device = "/dev/disk/by-uuid/6fcadafb-09dc-4e69-926c-608acb0798f7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/57D0-9D0C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-9b198792-4f79-44e0-a9d0-d9cdbbaa08fb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
