vim.keymap.set("n", "<leader>ff", function()
	require("fff").find_files()
end, { desc = "Find Files (fff)" })
vim.keymap.set("n", "<leader>/", function()
	require("fff").live_grep()
end, { desc = "Live Grep (fff)" })
vim.keymap.set("n", "<leader>fz", function()
	require("fff").live_grep({ grep = { modes = { "fuzzy", "plain" } } })
end, { desc = "Live Fuzzy Grep (fff)" })
vim.keymap.set({ "n", "x" }, "<leader>fw", function()
	require("fff").live_grep_under_cursor()
end, { desc = "Search current word / selection (fff)" })
